// Assemble the per-type fragments in src/defs/ and src/strings/ into the two
// bundle files Cavalry reads, writing them into the install-ready plugin folder
// beside the shaders. Run after editing any fragment:
//     node src/build.cjs
//
// The plugin folder is deliberately FLAT: definitions.json references shaders by
// bare filename, so every .sksl has to sit next to it. That folder is exactly
// what ships - drag it, or a zip of it, into the Cavalry window.
//
// Pass --deploy to also copy it into the live plugins folder, which is only
// useful when iterating; a plain drag-and-drop install does not need it.
const fs = require("fs"), path = require("path");

const ROOT   = path.join(__dirname, "..");
const PLUGIN = path.join(ROOT, "Field Kit");

const read = d => fs.readdirSync(path.join(__dirname, d))
    .filter(f => f.endsWith(".json")).sort()
    .map(f => JSON.parse(fs.readFileSync(path.join(__dirname, d, f), "utf8")));

const defs = read("defs");
const generated = new Set();
const templates = new Set();   // sources that were baked out; not orphans
fs.writeFileSync(path.join(PLUGIN, "strings.json"), JSON.stringify(read("strings"), null, 2));
console.log("types: " + defs.map(d => d.type).join(", "));

// presets.json ships the original looks of the filters that were merged, so a
// merged node can be put back to any of its predecessors in one click. Each
// fragment is an array, so they concatenate rather than nest.
const presets = read("presets").flat();
fs.writeFileSync(path.join(PLUGIN, "presets.json"), JSON.stringify(presets, null, 2));
console.log(presets.length + " presets");

// PER-PASS CONSTANTS ARE A 2.8 FEATURE. Cavalry 2.7.2's pass spec knows only
// skslFile, uniforms, blendMode and clearColor - a `constants` block there is
// ignored, the shader's `uniform float segIndex` is never bound, and the pass
// fails to CONSTRUCT with a bare "Pass N: buildShader failed" and no SkSL
// error. Every filter that reuses one shader across passes hit this.
//
// So the source keeps authoring with `constants` - one file per job, which is
// the whole point of them - and the BUILD bakes each variant out to its own
// file with the value as a `const`. The result runs identically on 2.8 and
// works on 2.7.2, with no version gate and nothing to keep in sync by hand.
for (const t of defs) {
    (t.passes || []).forEach((pass, passIndex) => {
        const consts = pass.constants || {};
        const src0 = fs.readFileSync(path.join(PLUGIN, pass.skslFile), "utf8");
        // 2.7.2 also REQUIRES `original` on every pass after the first - see the
        // note in displayMask.sksl. A shader shared between pass 0 and a later
        // pass cannot declare it in source, since pass 0 must not have it, so
        // the variant gets it here.
        // `original` does not exist for thirdPartyShader at all - the SDK says
        // so explicitly. Injecting it there would add an input the host never
        // binds, so a generator's later passes must be left alone.
        const isShader = t.superType === "thirdPartyShader";
        const needsOriginal = !isShader && passIndex >= 1
            && !/^uniform\s+shader\s+original\s*;/m.test(src0);
        if (!Object.keys(consts).length && !needsOriginal) { return; }
        const src = src0;
        const tag = Object.entries(consts)
            .map(([k, v]) => `${k}${String(v).replace(/[^0-9a-zA-Z]/g, "_")}`).join("_")
            + (needsOriginal ? "_orig" : "");
        const outName = pass.skslFile.replace(/\.sksl$/, `__${tag}.sksl`);
        let baked = src;
        for (const [k, v] of Object.entries(consts)) {
            const re = new RegExp(`^uniform\\s+float\\s+${k}\\s*;.*$`, "m");
            if (!re.test(baked)) {
                console.error(`MISSING: ${pass.skslFile} has no "uniform float ${k};" for its constant`);
                process.exit(1);
            }
            baked = baked.replace(re, `const float ${k} = ${Number(v).toFixed(6)};   // baked from the pass constant`);
        }
        if (needsOriginal) {
            const lines = baked.split("\n");
            let last = -1;
            lines.forEach((l, i) => { if (/^uniform\s+shader\s/.test(l)) { last = i; } });
            lines.splice(last + 1, 0, "uniform shader original;   // added by the build for Cavalry 2.7.2");
            baked = lines.join("\n");
        }
        fs.writeFileSync(path.join(PLUGIN, outName),
            `// GENERATED by src/build.cjs from ${pass.skslFile} - do not edit.\n` +
            `// Pass constants baked in so this runs on Cavalry 2.7.2, whose pass\n` +
            `// spec has no \`constants\` support. Edit the source file instead.\n` + baked);
        templates.add(pass.skslFile);
        pass.skslFile = outName;
        delete pass.constants;
        generated.add(outName);
    });
}

// Every shader the definitions ask for must be present and flat, or Cavalry
// registers the types and then silently fails to find their code.
const wanted = new Set();
for (const t of defs) {
    if (t.skslFile) { wanted.add(t.skslFile); }
    for (const p of (t.passes || [])) { wanted.add(p.skslFile); }
}
const missing = [...wanted].filter(f => !fs.existsSync(path.join(PLUGIN, f)));
if (missing.length) {
    console.error("MISSING shaders in the plugin folder: " + missing.join(", "));
    process.exit(1);
}
const present = fs.readdirSync(PLUGIN).filter(f => f.endsWith(".sksl"));
// A template is an input to the bake above, so it is deliberately unreferenced.
// Generated variants from an earlier build whose name has since changed are
// stale, not orphans - delete them rather than warning about them forever.
for (const f of present) {
    if (f.includes("__") && !wanted.has(f)) { fs.rmSync(path.join(PLUGIN, f)); }
}
const orphans = fs.readdirSync(PLUGIN).filter(f => f.endsWith(".sksl"))
    .filter(f => !wanted.has(f) && !templates.has(f));
if (orphans.length) { console.warn("unreferenced shaders: " + orphans.join(", ")); }
fs.writeFileSync(path.join(PLUGIN, "definitions.json"), JSON.stringify(defs, null, 2));
console.log(wanted.size + " shaders referenced, all present" + (generated.size ? ", " + generated.size + " generated for 2.7.2" : ""));

if (process.argv.includes("--deploy")) {
    const LIVE = path.join(process.env.HOME,
        "Library/Application Support/Cavalry/Third-Party/Plugins/Field Kit");
    fs.mkdirSync(LIVE, { recursive: true });
    const icons = fs.readdirSync(PLUGIN).filter(f => f.endsWith(".png"));
    const keep = new Set(["definitions.json", "strings.json", "presets.json",
        ...wanted, ...icons]);
    for (const f of fs.readdirSync(LIVE)) {
        if (f === ".DS_Store") { continue; }
        if (!keep.has(f)) { fs.rmSync(path.join(LIVE, f), { recursive: true, force: true }); }
    }
    for (const f of keep) { fs.copyFileSync(path.join(PLUGIN, f), path.join(LIVE, f)); }
    console.log("deployed " + keep.size + " files to " + LIVE);
}
